/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_jeune" rotation={[0.004, 0.025, 0.002]} scale={0.151}>
          <skinnedMesh
            name="Jeune"
            geometry={nodes.Jeune.geometry}
            material={materials['color_main.003']}
            skeleton={nodes.Jeune.skeleton}
          />
          <primitive object={nodes.root} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model3.gltf')
